version: 2.1

executors:
  go:
    parameters:
      goversion:
        type: string
        default: "15"
    docker:
      - image: circleci/golang:1.<< parameters.goversion >>
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/honeycombio/opentelemetry-exporter-go

jobs:
  test_opentelemetry:
    parameters:
      goversion:
        type: string
        default: "14"
    executor:
      name: go
      goversion: "<< parameters.goversion >>"
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -race -v ./...

workflows:
  build:
    jobs:
      - test_opentelemetry:
          goversion: "14"
      - test_opentelemetry:
          goversion: "15"
